feat: convert to lib
privanote/ui pull request #15
Opened 2024-02-22 03:53 UTC by oliviergoulet5

2024-02-26 12:31 UTC, thejasonxie commented on package.json
I think for this to work, you may need to specify "main", "module", and prefereable a "types" value since we are using typescript, pointing to files generated in the /dist

2024-02-26 12:35 UTC, thejasonxie requested changes
May also need to setup changesets for automated versioning and publishing?

2024-02-26 12:35 UTC, thejasonxie commented on vite.config.js
- use "vite-plugin-dts" to generate types.
- we may also want to see if there is a plugin to embed image data into the .js file so it does not need to be imported? That's only if this library will use images in its components i guess. Just thought of this because I noticed images was added to the dist directory when building

2024-02-26 14:10 UTC, thejasonxie commented on package.json
also might need this too
``` json
...
"publishConfig": {
    "@privanote:registry": "https://npm.pkg.github.com"
  }
...
```

2024-03-16 18:59 UTC, oliviergoulet5 commented on package.json
> I think for this to work, you may need to specify "main", "module", and prefereable a "types" value since we are using typescript, pointing to files generated in the /dist

I had both of these

I added the `publishConfig`.

2024-03-16 19:24 UTC, oliviergoulet5 commented on vite.config.js
I'll do the automated versioning and publishing after I validate it works the usual manual way.

2024-03-16 19:27 UTC, merged